### ISSUE TITLE
Please wait with changes of the adapter. I completely changed it.

### ISSUE THREAD

**Issue by GermanBluefox** [foxthefox/ioBroker.milight#2]
I am working now on milight too and changed the variables. My version will support the V6.
I want to finish it this week and merge the changes back.
https://github.com/GermanBluefox/ioBroker.milight

**Comment by foxthefox** [comment]
Ups, die Meldung hab ich glatt übersehen. Aber ich habe in den letzten Tagen eh nur an einem widget rumgebastelt. Die heutigen Bereinigungen/neuen Dateien waren mehr zur Vervollständigung um es auf npm hochzuladen und den Kriterien für ioBroker zu entsprechen.

**Comment by foxthefox** [comment]
merge is done.
testing is ongoing

**Comment by GermanBluefox** [comment]
Perfect. Thank you.

2017-01-24 23:35 GMT+01:00 foxthefox <notifications@github.com>:

**Comment by foxthefox** [comment]
what does mean it, when "adapter.setForeignState(id, true, true)" is made?
web adapter does send the command and milight adapter reacts accordingly, why is necessary to set "ForeignState"?
and why is used setForeignState and not setState?

**Comment by GermanBluefox** [comment]
The difference between setState and setForeignState is, that setState checks and if id does not start with "milight.0" it adds to ID this and then calls setForeignState. 
Because our IDs are full IDs (with milight.0) it is 0.0001ms :) faster to execute setForeignState because no need to check the ID.

**Comment by GermanBluefox** [comment]
Look at description of setObject here https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/adapter.js#L775

**Comment by foxthefox** [comment]
and why do we write/store the state again?

It is already stored via the Action from vis and we are inside Adapter.on('state change').
I experience problems with the 30s Switch OFF of the lamp again, which could be caused by this.
