### ISSUE TITLE
Update stable version in repo from 0.3.6 to 0.4.0

### ISSUE THREAD

**Issue by GermanBluefox** [foxthefox/ioBroker.milight#44]
# Think about update stable version to 0.4.0
**Version**: stable=**0.3.6** (1426 days old) => latest=**0.4.0** (79 days old)
**Installs**: stable=**769** (84.32%), latest=**100** (10.96%), total=**912**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L1354)

**Comment by mcm1957** [comment]
A kind reminder.
Is there any reason to delay an update of stable revision?

Feel free to drop a simple note if I should trigger an update.

**Comment by mcm1957** [comment]
@foxthefox 
Is there any reason to delay updating stable any longer?
Please drop a commit if you know any reason to refrain from updating.

**If there is no response within the next 30 days, we could decide to update anyway.**

**Comment by foxthefox** [comment]
no. there no reason for updating stable. I already started on a new version, but was interrupted

**Comment by mcm1957** [comment]
on hold as standard github tests are missing

**Comment by GermanBluefox** [comment]
This issue seems to be outdated.

This issue suggests to update the stable version of this adapter to 0.4.0 but the current stable version is already 0.4.0.

So this issue should be closed.
